[package]
name = "crypter"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
argon2 = "0.5.3"
clap = { version = "4.5.49", features = ["derive"] }
rand = "0.9.2"
rpassword = "7.4.0"
